### ISSUE TITLE
[FQR] Improve design, add types to access Clerk object as window

### ISSUE THREAD

**Issue by Supernova3339** [Triv2/ecom#1]
This is a reminder for me to add this, will entail all features below:

- [x]  redo user button to use shadcn's, have a dropdown instead. 

- [x] redo some design elements to be slightly smoother

- [x]  potentially set clerk appearance to dark from **ClerkProvider**

- [ ]  add sample layout area for ecommerce business side? {stores/{storeId}} - uuid for storeId??

**Comment by Supernova3339** [comment]
DB provider is not setup, layout will be added still but have no data sent to it ( except for user's name )

**Comment by Trivial-Lore** [comment]
I will setup the DB now, and get it organized so we can start building the layout side of things. I have a layout mockup was going with
<img src="https://github.com/Triv2/ecom/assets/126743500/3d5c4959-ee0b-4061-b484-9e8e0143bb05)" width={800} height={600} alt="diagram"/>

**Comment by Supernova3339** [comment]
> I will setup the DB now, and get it organized so we can start building the layout side of things. I have a layout mockup was going with <img alt="diagram" width="{800}" height="{600}" src="https://private-user-images.githubusercontent.com/126743500/299330764-3d5c4959-ee0b-4061-b484-9e8e0143bb05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxMjQ4ODIsIm5iZiI6MTcwNjEyNDU4MiwicGF0aCI6Ii8xMjY3NDM1MDAvMjk5MzMwNzY0LTNkNWM0OTU5LWVlMGItNDA2MS1iNDg0LTllOGUwMTQzYmIwNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNFQxOTI5NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YjRhNmFhNDA0ZmMwZDBlZTg5MzUxNmEzMzBlZjkxNDgwNjMzNGRlOGI3N2Q4YTFhZmU3ZjFiOTQ2ODdkYTFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8Utbe99_8Mj4yP_4R7rPDeMxI3KPfpC3yeuchqvLYiU">

for a searchbar, instead do a command palette and have a button for mobile devices

**Comment by Trivial-Lore** [comment]
Before making that layout, went through and looked at some other mock-ups. Found that my first design wasn't efficient. Thinking about implementing something more condensed like the chrome web store. 
<img src="https://github.com/Triv2/ecom/assets/126743500/ff185195-be16-41d7-b3a6-eb56f45dd98e" alt="img" width={600} height={300}/>

**Comment by Supernova3339** [comment]
for layouts, looking here:
https://tailwindui.com/components/application-ui/application-shells/sidebar

whatever sounds coolest let me know and I'll grab it for you.
